# Generated by Django 4.2.26 on 2025-11-27 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormYapilandirma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Müşteri Form Yapılandırması',
                'verbose_name_plural': 'Müşteri Form Yapılandırması',
            },
        ),
        migrations.CreateModel(
            name='AlanTanim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=100, verbose_name='Alan Adı (Etiket)')),
                ('input_type', models.CharField(choices=[('CharField', 'Metin Kutusu (Kısa)'), ('TextField', 'Metin Kutusu (Uzun)'), ('IntegerField', 'Sayı'), ('DateField', 'Tarih'), ('BooleanField', 'Onay Kutusu (Evet/Hayır)')], default='CharField', max_length=20, verbose_name='Veri Tipi')),
                ('zorunlu', models.BooleanField(default=False, verbose_name='Zorunlu mu?')),
                ('sira', models.PositiveSmallIntegerField(default=0, verbose_name='Sıralama')),
                ('form_yapilandirma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alanlar', to='core.formyapilandirma')),
            ],
            options={
                'verbose_name': 'Form Alanı',
                'verbose_name_plural': 'Form Alanları',
                'ordering': ['sira'],
            },
        ),
    ]
