# Generated by Django 4.2.26 on 2025-11-27 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alantanim',
            name='listede_goster',
            field=models.BooleanField(default=False, verbose_name='Listede Göster (Hızlı Bakış)'),
        ),
    ]
