# Generated by Django 4.2.26 on 2025-11-27 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alantanim_listede_goster'),
    ]

    operations = [
        migrations.AddField(
            model_name='alantanim',
            name='arama_varmi',
            field=models.BooleanField(default=True, verbose_name='Arama Yapılsın mı?'),
        ),
        migrations.AlterField(
            model_name='alantanim',
            name='listede_goster',
            field=models.BooleanField(default=False, verbose_name='Listede Göster'),
        ),
    ]
