# Generated by Django 4.2.26 on 2025-11-27 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alantanim_arama_varmi_alter_alantanim_listede_goster'),
    ]

    operations = [
        migrations.CreateModel(
            name='PdfAyarlari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firma_adi', models.CharField(max_length=200, verbose_name='Firma Ünvanı')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logolar/', verbose_name='Firma Logosu')),
                ('adres', models.TextField(blank=True, verbose_name='Firma Adresi')),
                ('telefon', models.CharField(blank=True, max_length=50, verbose_name='Telefon')),
                ('eposta', models.EmailField(blank=True, max_length=254, verbose_name='E-Posta')),
                ('web_site', models.URLField(blank=True, verbose_name='Web Sitesi')),
                ('banka_bilgileri', models.TextField(blank=True, help_text="PDF'in en altında görünecek IBAN vb. bilgiler", verbose_name='Banka Bilgileri (Alt Bilgi)')),
            ],
            options={
                'verbose_name': 'PDF & Firma Ayarları',
                'verbose_name_plural': 'PDF & Firma Ayarları',
            },
        ),
    ]
