# Generated by Django 4.2.26 on 2025-11-27 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_pdfayarlari'),
    ]

    operations = [
        migrations.CreateModel(
            name='SartMaddesi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icerik', models.TextField(help_text='Örn: Ödeme %50 peşin, %50 teslimdedir.', verbose_name='Madde İçeriği')),
            ],
            options={
                'verbose_name': 'Standart Şart Maddesi',
                'verbose_name_plural': 'Standart Şart Maddeleri',
            },
        ),
        migrations.CreateModel(
            name='SartSablonu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(help_text='Örn: Standart Hizmet Sözleşmesi', max_length=100, verbose_name='Şablon Adı')),
                ('maddeler', models.ManyToManyField(to='core.sartmaddesi', verbose_name='İçerdiği Maddeler')),
            ],
            options={
                'verbose_name': 'Şart Şablonu',
                'verbose_name_plural': 'Şart Şablonları',
            },
        ),
    ]
