# Generated by Django 4.2.26 on 2025-11-27 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_sartmaddesi_sartsablonu'),
    ]

    operations = [
        migrations.CreateModel(
            name='DovizKuru',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kod', models.CharField(help_text='Örn: USD, EUR, TRY', max_length=10, unique=True, verbose_name='Para Birimi Kodu')),
                ('ad', models.CharField(max_length=50, verbose_name='Para Birimi Adı')),
                ('alis', models.DecimalField(decimal_places=4, default=1.0, max_digits=10, verbose_name='Alış Kuru')),
                ('satis', models.DecimalField(decimal_places=4, default=1.0, max_digits=10, verbose_name='Satış Kuru')),
                ('son_guncelleme', models.DateTimeField(auto_now=True, verbose_name='Son Güncelleme')),
            ],
            options={
                'verbose_name': 'Döviz Kuru',
                'verbose_name_plural': 'Döviz Kurları',
            },
        ),
    ]
