# Generated by Django 4.2.26 on 2025-11-27 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=100, verbose_name='Kategori Adı')),
            ],
            options={
                'verbose_name': 'Ürün Kategorisi',
                'verbose_name_plural': 'Ürün Kategorileri',
            },
        ),
        migrations.CreateModel(
            name='Urun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kod', models.CharField(max_length=50, unique=True, verbose_name='Ürün Kodu / SKU')),
                ('ad', models.CharField(max_length=200, verbose_name='Ürün Adı')),
                ('satis_fiyati', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Satış Fiyatı')),
                ('stok_miktari', models.IntegerField(default=0, verbose_name='Mevcut Stok')),
                ('kritik_stok_seviyesi', models.IntegerField(default=10, help_text='Stok bu sayının altına düşerse uyarı verir.', verbose_name='Kritik Stok Uyarısı')),
                ('aktif', models.BooleanField(default=True, verbose_name='Satışta mı?')),
                ('kategori', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stok.kategori', verbose_name='Kategori')),
            ],
            options={
                'verbose_name': 'Ürün / Hizmet',
                'verbose_name_plural': 'Ürünler / Hizmetler',
            },
        ),
    ]
