# Generated by Django 4.2.26 on 2025-11-27 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_dovizkuru'),
        ('stok', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='urun',
            name='para_birimi',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='core.dovizkuru', verbose_name='Para Birimi'),
        ),
    ]
