# Generated by Django 4.2.26 on 2025-11-28 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stok', '0002_urun_para_birimi'),
    ]

    operations = [
        migrations.AddField(
            model_name='urun',
            name='bakim_periyodu',
            field=models.PositiveIntegerField(default=0, help_text='0 ise bakım gerektirmez. Örneğin 6 yazarsanız, satıştan 6 ay sonra uyarı verir.', verbose_name='Bakım Periyodu (Ay)'),
        ),
    ]
