# Generated by Django 4.2.26 on 2025-11-29 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stok', '0003_urun_bakim_periyodu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urun',
            name='bakim_periyodu',
            field=models.PositiveIntegerField(default=0, help_text='0: Bakım gerektirmez. Örn: 6 yazarsanız, her 6 ayda bir bakım uyarısı verir.', verbose_name='Bakım Periyodu (Ay)'),
        ),
        migrations.AlterField(
            model_name='urun',
            name='kritik_stok_seviyesi',
            field=models.IntegerField(default=10, verbose_name='Kritik Stok Uyarısı'),
        ),
    ]
