# Generated by Django 4.2.26 on 2025-11-29 12:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0007_userprofile'),
        ('stok', '0004_alter_urun_bakim_periyodu_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalUrun',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('kod', models.CharField(db_index=True, max_length=50, verbose_name='Ürün Kodu / SKU')),
                ('ad', models.CharField(max_length=200, verbose_name='Ürün Adı')),
                ('satis_fiyati', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Satış Fiyatı')),
                ('stok_miktari', models.IntegerField(default=0, verbose_name='Mevcut Stok')),
                ('kritik_stok_seviyesi', models.IntegerField(default=10, verbose_name='Kritik Stok Uyarısı')),
                ('aktif', models.BooleanField(default=True, verbose_name='Satışta mı?')),
                ('bakim_periyodu', models.PositiveIntegerField(default=0, help_text='0: Bakım gerektirmez. Örn: 6 yazarsanız, her 6 ayda bir bakım uyarısı verir.', verbose_name='Bakım Periyodu (Ay)')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('kategori', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='stok.kategori', verbose_name='Kategori')),
                ('para_birimi', models.ForeignKey(blank=True, db_constraint=False, default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.dovizkuru', verbose_name='Para Birimi')),
            ],
            options={
                'verbose_name': 'historical Ürün / Hizmet',
                'verbose_name_plural': 'historical Ürünler / Hizmetler',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
