# Generated by Django 4.2.26 on 2025-11-27 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('musteri', '0002_remove_musteri_ad_soyad_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proforma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarih', models.DateField(verbose_name='Teklif Tarihi')),
                ('gecerlilik_tarihi', models.DateField(blank=True, null=True, verbose_name='Son Geçerlilik Tarihi')),
                ('kod', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Teklif No')),
                ('notlar', models.TextField(blank=True, verbose_name='Notlar/Şartlar')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('musteri', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musteri.musteri', verbose_name='Müşteri')),
            ],
            options={
                'verbose_name': 'Proforma Teklif',
                'verbose_name_plural': 'Proforma Teklifler',
            },
        ),
        migrations.CreateModel(
            name='ProformaKalemi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urun_hizmet', models.CharField(max_length=200, verbose_name='Ürün/Hizmet Adı')),
                ('aciklama', models.CharField(blank=True, max_length=200, verbose_name='Açıklama')),
                ('miktar', models.PositiveIntegerField(default=1, verbose_name='Miktar')),
                ('birim_fiyat', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Birim Fiyat')),
                ('kdv_orani', models.PositiveIntegerField(default=20, verbose_name='KDV %')),
                ('proforma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kalemler', to='teklif.proforma')),
            ],
            options={
                'verbose_name': 'Teklif Kalemi',
                'verbose_name_plural': 'Teklif Kalemleri',
            },
        ),
    ]
