# Generated by Django 4.2.26 on 2025-11-27 13:27

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('teklif', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proforma',
            name='notlar',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Notlar/Şartlar'),
        ),
    ]
