# Generated by Django 4.2.26 on 2025-11-27 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stok', '0001_initial'),
        ('teklif', '0002_alter_proforma_notlar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proformakalemi',
            name='urun_hizmet',
        ),
        migrations.AddField(
            model_name='proformakalemi',
            name='urun',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='stok.urun', verbose_name='Ürün Seçimi'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='proformakalemi',
            name='aciklama',
            field=models.CharField(blank=True, max_length=200, verbose_name='Açıklama (Opsiyonel)'),
        ),
        migrations.AlterField(
            model_name='proformakalemi',
            name='birim_fiyat',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Birim Fiyat'),
        ),
    ]
