# Generated by Django 4.2.26 on 2025-11-27 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teklif', '0003_remove_proformakalemi_urun_hizmet_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proforma',
            options={'ordering': ['-created_at'], 'verbose_name': 'Proforma Teklif', 'verbose_name_plural': 'Proforma Teklifler'},
        ),
        migrations.AddField(
            model_name='proforma',
            name='mail_gonderim_tarihi',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Mail Gönderim Tarihi'),
        ),
    ]
