# Generated by Django 4.2.26 on 2025-11-27 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teklif', '0004_alter_proforma_options_proforma_mail_gonderim_tarihi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proforma',
            name='mail_gonderim_tarihi',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Son Mail Tarihi'),
        ),
        migrations.CreateModel(
            name='MailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gonderilen_adres', models.EmailField(max_length=254, verbose_name='Gönderilen Adres')),
                ('gonderim_zamani', models.DateTimeField(auto_now_add=True, verbose_name='Gönderim Zamanı')),
                ('proforma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mail_logs', to='teklif.proforma')),
            ],
            options={
                'verbose_name': 'Mail Kaydı',
                'verbose_name_plural': 'Mail Kayıtları',
                'ordering': ['-gonderim_zamani'],
            },
        ),
    ]
