# Generated by Django 4.2.26 on 2025-11-27 15:45

from django.db import migrations, models
import django.db.models.deletion
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('teklif', '0005_alter_proforma_mail_gonderim_tarihi_maillog'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeklifDurumu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=50, verbose_name='Durum Adı')),
                ('renk', models.CharField(default='#6c757d', help_text='Örn: #28a745 (Yeşil), #dc3545 (Kırmızı)', max_length=20, verbose_name='Renk Kodu (Hex)')),
                ('onaylandi_mi', models.BooleanField(default=False, help_text='Bu durum seçildiğinde teklif kilitlenir veya satışa döner.', verbose_name='Onaylanmış Sayılsın mı?')),
            ],
            options={
                'verbose_name': 'Teklif Durumu',
                'verbose_name_plural': 'Teklif Durum Tanımları',
            },
        ),
        migrations.AlterField(
            model_name='proforma',
            name='notlar',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Notlar (Genel Açıklama)'),
        ),
        migrations.CreateModel(
            name='TeklifSarti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aciklama', models.CharField(max_length=500, verbose_name='Şart Maddesi')),
                ('sira', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
                ('proforma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sartlar', to='teklif.proforma')),
            ],
            options={
                'verbose_name': 'Teklif Şartı',
                'verbose_name_plural': 'Teklif Şartları',
                'ordering': ['sira'],
            },
        ),
        migrations.AddField(
            model_name='proforma',
            name='durum',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='teklif.teklifdurumu', verbose_name='Teklif Durumu'),
        ),
    ]
