# Generated by Django 4.2.26 on 2025-11-27 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teklif', '0006_teklifdurumu_alter_proforma_notlar_teklifsarti_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teklifsarti',
            options={'ordering': ['sira'], 'verbose_name': 'Şart Maddesi', 'verbose_name_plural': 'Teklif Şartları'},
        ),
        migrations.AlterField(
            model_name='teklifsarti',
            name='aciklama',
            field=models.TextField(verbose_name='Şart Maddesi'),
        ),
    ]
