# Generated by Django 4.2.26 on 2025-11-27 16:11

from django.db import migrations, models
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('teklif', '0007_alter_teklifsarti_options_alter_teklifsarti_aciklama'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proforma',
            name='durum',
            field=models.CharField(choices=[('hazirlik', 'Hazırlık'), ('gonderildi', 'Gönderildi'), ('onaylandi', 'Onaylandı'), ('reddedildi', 'Reddedildi'), ('iptal', 'İptal')], default='hazirlik', max_length=20, verbose_name='Teklif Durumu'),
        ),
        migrations.AlterField(
            model_name='proforma',
            name='notlar',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Notlar'),
        ),
        migrations.DeleteModel(
            name='TeklifDurumu',
        ),
    ]
