# Generated by Django 4.2.26 on 2025-11-27 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_sartmaddesi_sartsablonu'),
        ('teklif', '0008_alter_proforma_durum_alter_proforma_notlar_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maillog',
            options={'ordering': ['-gonderim_zamani'], 'verbose_name': 'Mail Kaydı', 'verbose_name_plural': 'Mail Gönderim Geçmişi'},
        ),
        migrations.AddField(
            model_name='proforma',
            name='sart_sablonu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.sartsablonu', verbose_name='Şart Şablonu'),
        ),
        migrations.DeleteModel(
            name='TeklifSarti',
        ),
    ]
