# Generated by Django 4.2.26 on 2025-11-27 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_dovizkuru'),
        ('teklif', '0010_proforma_para_birimi'),
    ]

    operations = [
        migrations.AddField(
            model_name='proformakalemi',
            name='para_birimi',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='core.dovizkuru', verbose_name='Kur'),
        ),
    ]
