# Generated by Django 4.2.26 on 2025-11-27 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teklif', '0011_proformakalemi_para_birimi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proforma',
            name='para_birimi',
        ),
        migrations.AddField(
            model_name='proforma',
            name='firma_ici_not',
            field=models.TextField(blank=True, help_text='Bu not müşteriye görünmez, sadece panelde görünür.', verbose_name='Firma İçi Not (Gizli)'),
        ),
    ]
