# Generated by Django 4.2.26 on 2025-11-28 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_dovizkuru'),
        ('teklif', '0012_remove_proforma_para_birimi_proforma_firma_ici_not'),
    ]

    operations = [
        migrations.AddField(
            model_name='proforma',
            name='para_birimi',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='core.dovizkuru', verbose_name='Para Birimi'),
        ),
        migrations.AlterField(
            model_name='proforma',
            name='firma_ici_not',
            field=models.TextField(blank=True, help_text='Bu not müşteriye görünmez.', verbose_name='Firma İçi Not (Gizli)'),
        ),
    ]
