# Generated by Django 4.2.26 on 2025-11-28 20:34

from django.db import migrations, models
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('teklif', '0013_proforma_para_birimi_alter_proforma_firma_ici_not'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proforma',
            name='para_birimi',
        ),
        migrations.AlterField(
            model_name='proforma',
            name='firma_ici_not',
            field=models.TextField(blank=True, verbose_name='Firma İçi Not (Gizli)'),
        ),
        migrations.AlterField(
            model_name='proforma',
            name='notlar',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Not'),
        ),
    ]
