# Generated by Django 4.2.26 on 2025-11-28 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teklif', '0014_remove_proforma_para_birimi_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proformakalemi',
            name='birim_fiyat',
        ),
        migrations.RemoveField(
            model_name='proformakalemi',
            name='para_birimi',
        ),
    ]
