# Generated by Django 4.2.26 on 2025-11-29 12:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_ckeditor_5.fields
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('musteri', '0002_remove_musteri_ad_soyad_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0007_userprofile'),
        ('teklif', '0015_remove_proformakalemi_birim_fiyat_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalProforma',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('durum', models.CharField(choices=[('hazirlik', 'Hazırlık'), ('gonderildi', 'Gönderildi'), ('onaylandi', 'Onaylandı'), ('reddedildi', 'Reddedildi'), ('iptal', 'İptal')], default='hazirlik', max_length=20, verbose_name='Teklif Durumu')),
                ('tarih', models.DateField(verbose_name='Teklif Tarihi')),
                ('gecerlilik_tarihi', models.DateField(blank=True, null=True, verbose_name='Son Geçerlilik Tarihi')),
                ('kod', models.CharField(db_index=True, editable=False, max_length=20, verbose_name='Teklif No')),
                ('notlar', django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Not')),
                ('firma_ici_not', models.TextField(blank=True, verbose_name='Firma İçi Not (Gizli)')),
                ('mail_gonderim_tarihi', models.DateTimeField(blank=True, null=True, verbose_name='Son Mail Tarihi')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('musteri', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='musteri.musteri', verbose_name='Müşteri')),
                ('sart_sablonu', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.sartsablonu', verbose_name='Şart Şablonu')),
            ],
            options={
                'verbose_name': 'historical Proforma Teklif',
                'verbose_name_plural': 'historical Proforma Teklifler',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
