# Generated by Django 4.2.26 on 2025-11-28 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('musteri', '0002_remove_musteri_ad_soyad_and_more'),
        ('stok', '0003_urun_bakim_periyodu'),
        ('teklif', '0013_proforma_para_birimi_alter_proforma_firma_ici_not'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServisKaydi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fis_no', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Servis Fiş No')),
                ('konu', models.CharField(max_length=200, verbose_name='Servis Konusu / Arıza')),
                ('aciklama', models.TextField(blank=True, verbose_name='Teknisyen Notları / Arıza Detayı')),
                ('planlanan_tarih', models.DateTimeField(verbose_name='Planlanan Randevu')),
                ('tamamlanma_tarihi', models.DateTimeField(blank=True, null=True, verbose_name='Tamamlanma Tarihi')),
                ('durum', models.CharField(choices=[('bekliyor', 'Bekliyor / Atandı'), ('islemde', 'İşlemde'), ('parca_bekleniyor', 'Yedek Parça Bekleniyor'), ('tamamlandi', 'Tamamlandı (İmza Bekleniyor)'), ('kapandi', 'Kapandı / Teslim Edildi'), ('iptal', 'İptal')], default='bekliyor', max_length=20, verbose_name='Durum')),
                ('musteri_imzasi', models.TextField(blank=True, null=True, verbose_name='Müşteri İmzası (Data)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ilgili_proforma', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='teklif.proforma', verbose_name='Bağlı Teklif/Proforma')),
                ('ilgili_urun', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stok.urun', verbose_name='İlgili Ürün')),
                ('musteri', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musteri.musteri', verbose_name='Müşteri')),
            ],
            options={
                'verbose_name': 'Servis Kaydı',
                'verbose_name_plural': 'Servis Kayıtları',
                'ordering': ['-planlanan_tarih'],
            },
        ),
        migrations.CreateModel(
            name='YapilanIslem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aciklama', models.CharField(max_length=255, verbose_name='Yapılan İşlem')),
                ('tamamlandi', models.BooleanField(default=True, verbose_name='Tamamlandı')),
                ('servis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='islemler', to='servis.serviskaydi')),
            ],
            options={
                'verbose_name': 'Yapılan İşlem',
                'verbose_name_plural': 'Yapılan İşlemler (Checklist)',
            },
        ),
    ]
