# Generated by Django 4.2.26 on 2025-11-28 11:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stok', '0003_urun_bakim_periyodu'),
        ('servis', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviskaydi',
            name='ilgili_urun',
        ),
        migrations.AddField(
            model_name='serviskaydi',
            name='firma_ici_not',
            field=models.TextField(blank=True, verbose_name='Firma İçi Not (Gizli)'),
        ),
        migrations.AddField(
            model_name='serviskaydi',
            name='mail_gonderim_tarihi',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Son Mail Tarihi'),
        ),
        migrations.AddField(
            model_name='serviskaydi',
            name='teknisyenler',
            field=models.ManyToManyField(help_text='Servise gidecek personelleri seçiniz.', to=settings.AUTH_USER_MODEL, verbose_name='Görevli Teknisyenler'),
        ),
        migrations.AlterField(
            model_name='serviskaydi',
            name='aciklama',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Teknisyen Notları / Arıza Detayı'),
        ),
        migrations.AlterField(
            model_name='yapilanislem',
            name='tamamlandi',
            field=models.BooleanField(default=False, verbose_name='Tamamlandı'),
        ),
        migrations.CreateModel(
            name='ServisUrunleri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seri_no', models.CharField(blank=True, max_length=100, verbose_name='Seri No / Açıklama')),
                ('adet', models.PositiveIntegerField(default=1)),
                ('servis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='urunler', to='servis.serviskaydi')),
                ('urun', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stok.urun', verbose_name='Ürün')),
            ],
            options={
                'verbose_name': 'Servis Ürünü',
                'verbose_name_plural': 'Servis Ürünleri',
            },
        ),
    ]
