# Generated by Django 4.2.26 on 2025-11-28 11:42

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('servis', '0002_remove_serviskaydi_ilgili_urun_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeknisyenUser',
            fields=[
            ],
            options={
                'verbose_name': 'Teknisyen',
                'verbose_name_plural': 'Teknisyenler',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='serviskaydi',
            name='teknisyenler',
            field=models.ManyToManyField(help_text='Listeden seçip sağ tarafa atınız.', to='servis.teknisyenuser', verbose_name='Görevli Teknisyenler'),
        ),
    ]
