# Generated by Django 4.2.26 on 2025-11-28 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servis', '0003_teknisyenuser_alter_serviskaydi_teknisyenler'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviskaydi',
            name='durum',
            field=models.CharField(choices=[('bekliyor', 'Bekliyor / Atandı'), ('islemde', 'İşlemde'), ('parca_bekleniyor', 'Yedek Parça Bekleniyor'), ('imza_bekleniyor', 'İşlem Bitti (İmza Bekleniyor)'), ('tamamlandi', 'Tamamlandı / İmzalandı'), ('kapandi', 'Kapandı / Teslim Edildi'), ('iptal', 'İptal')], default='bekliyor', max_length=20, verbose_name='Durum'),
        ),
    ]
