# Generated by Django 4.2.26 on 2025-11-29 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stok', '0004_alter_urun_bakim_periyodu_and_more'),
        ('musteri', '0002_remove_musteri_ad_soyad_and_more'),
        ('servis', '0005_alter_serviskaydi_durum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviskaydi',
            name='teknisyenler',
            field=models.ManyToManyField(to='servis.teknisyenuser', verbose_name='Görevli Teknisyenler'),
        ),
        migrations.CreateModel(
            name='BakimPlani',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('son_bakim_tarihi', models.DateField(verbose_name='Son Bakım Tarihi')),
                ('gelecek_bakim_tarihi', models.DateField(verbose_name='Gelecek Bakım Tarihi')),
                ('aciklama', models.CharField(blank=True, max_length=200, verbose_name='Not')),
                ('musteri', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musteri.musteri', verbose_name='Müşteri')),
                ('son_servis', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='servis.serviskaydi', verbose_name='Son Yapılan Servis')),
                ('urun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stok.urun', verbose_name='Ürün')),
            ],
            options={
                'verbose_name': 'Yaklaşan Bakım',
                'verbose_name_plural': 'Yaklaşan Bakımlar',
                'ordering': ['gelecek_bakim_tarihi'],
            },
        ),
    ]
