# Generated by Django 4.2.26 on 2025-11-29 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servis', '0006_alter_serviskaydi_teknisyenler_bakimplani'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviskaydi',
            name='imza_atan_kisi',
            field=models.CharField(blank=True, help_text='Teslim alan kişinin Adı Soyadı', max_length=100, null=True, verbose_name='İmzalayan Kişi'),
        ),
    ]
