# Generated by Django 4.2.26 on 2025-11-29 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servis', '0007_serviskaydi_imza_atan_kisi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviskaydi',
            name='imza_atan_kisi',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='İmzalayan Kişi'),
        ),
        migrations.CreateModel(
            name='ServisMailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gonderilen_adres', models.EmailField(max_length=254, verbose_name='Gönderilen Adres')),
                ('gonderim_zamani', models.DateTimeField(auto_now_add=True, verbose_name='Gönderim Zamanı')),
                ('servis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mail_logs', to='servis.serviskaydi')),
            ],
            options={
                'verbose_name': 'Mail Kaydı',
                'verbose_name_plural': 'Mail Gönderim Geçmişi',
                'ordering': ['-gonderim_zamani'],
            },
        ),
    ]
