# Generated by Django 4.2.26 on 2025-11-29 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servis', '0008_alter_serviskaydi_imza_atan_kisi_servismaillog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviskaydi',
            name='durum',
            field=models.CharField(choices=[('bekliyor', 'Bekliyor / Atandı'), ('islemde', 'İşlemde'), ('parca_bekleniyor', 'Yedek Parça Bekleniyor'), ('imza_bekleniyor', 'İşlem Bitti (İmza Bekleniyor)'), ('tamamlandi', 'Tamamlandı'), ('iptal', 'İptal')], default='bekliyor', max_length=20, verbose_name='Durum'),
        ),
        migrations.CreateModel(
            name='BakimGecmisi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarih', models.DateField(verbose_name='İşlem Tarihi')),
                ('olusturulan_sonraki_tarih', models.DateField(verbose_name='Oluşturulan Sonraki Bakım Tarihi')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gecmis', to='servis.bakimplani')),
                ('servis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servis.serviskaydi', verbose_name='Yapılan Servis')),
            ],
            options={
                'verbose_name': 'Bakım Geçmişi',
                'verbose_name_plural': 'Bakım Geçmişi',
                'ordering': ['-tarih'],
            },
        ),
    ]
