# Generated by Django 4.2.26 on 2025-11-29 12:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_ckeditor_5.fields
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('musteri', '0002_remove_musteri_ad_soyad_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teklif', '0015_remove_proformakalemi_birim_fiyat_and_more'),
        ('servis', '0009_alter_serviskaydi_durum_bakimgecmisi'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalServisKaydi',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('fis_no', models.CharField(db_index=True, editable=False, max_length=20, verbose_name='Servis Fiş No')),
                ('konu', models.CharField(max_length=200, verbose_name='Servis Konusu / Arıza')),
                ('aciklama', django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Teknisyen Notları / Arıza Detayı')),
                ('firma_ici_not', models.TextField(blank=True, verbose_name='Firma İçi Not (Gizli)')),
                ('planlanan_tarih', models.DateTimeField(verbose_name='Planlanan Randevu')),
                ('tamamlanma_tarihi', models.DateTimeField(blank=True, null=True, verbose_name='Tamamlanma Tarihi')),
                ('durum', models.CharField(choices=[('bekliyor', 'Bekliyor / Atandı'), ('islemde', 'İşlemde'), ('parca_bekleniyor', 'Yedek Parça Bekleniyor'), ('imza_bekleniyor', 'İşlem Bitti (İmza Bekleniyor)'), ('tamamlandi', 'Tamamlandı'), ('iptal', 'İptal')], default='bekliyor', max_length=20, verbose_name='Durum')),
                ('musteri_imzasi', models.TextField(blank=True, null=True, verbose_name='Müşteri İmzası (Data)')),
                ('imza_atan_kisi', models.CharField(blank=True, max_length=100, null=True, verbose_name='İmzalayan Kişi')),
                ('mail_gonderim_tarihi', models.DateTimeField(blank=True, null=True, verbose_name='Son Mail Tarihi')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('ilgili_proforma', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='teklif.proforma', verbose_name='Bağlı Teklif/Proforma')),
                ('musteri', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='musteri.musteri', verbose_name='Müşteri')),
            ],
            options={
                'verbose_name': 'historical Servis Kaydı',
                'verbose_name_plural': 'historical Servis Kayıtları',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
