# Generated by Django 4.2.26 on 2025-11-27 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Musteri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_soyad', models.CharField(max_length=150, verbose_name='Müşteri Adı Soyadı')),
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True)),
                ('ekstra_bilgiler', models.JSONField(blank=True, default=dict, null=True)),
            ],
            options={
                'verbose_name': 'Müşteri',
                'verbose_name_plural': 'Müşteriler',
            },
        ),
    ]
