# Generated by Django 4.2.26 on 2025-11-27 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musteri', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='musteri',
            name='ad_soyad',
        ),
        migrations.AlterField(
            model_name='musteri',
            name='ekstra_bilgiler',
            field=models.JSONField(blank=True, default=dict, verbose_name='Müşteri Bilgileri'),
        ),
        migrations.AlterField(
            model_name='musteri',
            name='olusturulma_tarihi',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Kayıt Tarihi'),
        ),
    ]
